[package]
name = "penguin-farm"
description = "Non-fungible token pallet provides basic functions to create and manager NFT"



repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/nft"
license = "Apache-2.0"
version = "0.4.1-dev"
authors = ["kevin.li"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-std = { version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }
sp-runtime = { version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }
frame-system ={ version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }
pallet-timestamp ={ version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }
pallet-scheduler ={ version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }
pallet-nft = {default-features = false,path="../nft"}
orml-nft = {default-features = false,path="../orml/nft"}
pallet-assets = { default-features = false, path="../assets" }
sp-arithmetic = { version = "4.0.0-dev", default-features = false, git = "http://47.102.99.229:17000/block-chain/substrate-v2" }
log = { version = "0.4.14", default-features = false }


primitive={default-features = false, path="../../primitives/primitive"}

[dev-dependencies]
sp-io = { version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }
sp-core = { version = "4.0.0-dev", git = "http://47.102.99.229:17000/block-chain/substrate-v2", default-features = false }

[features]
default = ["std"]
std = [
	"log/std",
	"serde",
	"codec/std",
	"orml-nft/std",
	"pallet-nft/std",
	"sp-std/std",
	"sp-runtime/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-assets/std",
	"sp-arithmetic/std"

]
try-runtime = ["frame-support/try-runtime"]
